---
when:
  event: [tag, push, release, deployment, cron, manual]
  branch: [main]
steps:
  - name: build hugo
    image: alpine:edge
    commands:
      - export UMAMI_DOMAIN=$UMAMI_DOMAIN
      - export UMAMI_ID=$UMAMI_ID
      - apk update
      - apk add hugo
      - hugo -b 'https://music.guerilla.studio'
    secrets: [ 'umami_domain', 'umami_id' ]

  - name: upload
    when:
      branch:
        - main
    image: node:lts-alpine
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    commands:
      - npx --yes dxfl deploy music.guerilla.studio public/ --yes
