---
when:
  event: [tag, push, release, deployment, cron, manual]
  branch: [main]
steps:
  - name: build hugo
    image: alpine:3.20.3
    commands:
      - export UMAMI_DOMAIN=$UMAMI_DOMAIN
      - export UMAMI_ID=$UMAMI_ID
      - apk update
      - apk add hugo
      - hugo -b 'https://music.guerilla.studio'
    secrets: [ 'umami_domain', 'umami_id' ]

  - name: upload
    when:
      branch:
        - main
    image: woodpeckerci/s3
    settings:
      bucket: music.guerilla.studio
      endpoint: https://garage.deuxfleurs.fr
      region: garage
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      source: public/**/*
      target: /
      strip_prefix: public/
      path_style: true
