baseURL = "http://localhost:1312/"
languageCode = "en-us"
title = "Now Playing"
mainSections = ["a"]
[pagination]
  disableAliases = false
  pagerSize = 16
  path = 'page'
disableKinds = ["taxonomy"]
[params]
  description = "Collection of Handpicked Albums by Guérilla.Studio"
  [params.author]
    name = "Guérilla.Studio"
    url = "https://guerilla.studio"
  [params.creator]
    name = "Guérilla.Studio"
    url = "https://guerilla.studio"
  [params.hosting]
    name = "Deuxfleurs"
    url = "https://deuxfleurs.fr"
    prefixtext = "Big thanks to"
    suffixtext = "for providing an eco-responsible and distributed web hosting."

[imaging]
quality = 90
[security]
  [security.funcs]
  getenv = [ "^HUGO_", "CONTEXT", "URL", "BASE_URL", "UMAMI_DOMAIN", "UMAMI_ID" ]

## Deploy into a Garage bucket at Deuxfleurs
[[deployment.targets]]
URL = "s3://music.guerilla.studio&endpoint=garage.deuxfleurs.fr&region=garage&s3ForcePathStyle=true"
